version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:2000"
  db:
    image: postgres:alpine
    environment:
     POSTGRES_DB: eternal-fund
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 12345678  
